### ISSUE TITLE
Quote Report / Return characters are not printed in the article description (should have return between product name and description as well) 

### ISSUE THREAD

**Issue by timsmet** [timsmet/odoodc#18]
Like it is in the original report from Odoo ... (without the product number)

**Comment by rjpathan** [comment]
I think its because I am formatting description to remove product code while showing in the report.

Below attached 14.pdf report shows while description is formatted to remove product code
15.pdf shows description without formatting.

[Quote_SO001 (14).pdf](https://github.com/timsmet/odoodc/files/2522855/Quote_SO001.14.pdf)
[Quote_SO001 (15).pdf](https://github.com/timsmet/odoodc/files/2522856/Quote_SO001.15.pdf)

**Comment by rjpathan** [comment]
so, if we remove showing product code in description field when product is selected in the form view of the application, then it should fix this issue.

**Comment by timsmet** [comment]
Can you remove that ?.... was one of the next items anyway .... we do not really use this code

**Comment by rjpathan** [comment]
Fixed https://github.com/timsmet/odoodc/commit/0d2d4a9188a1dfc178129a54c89b8d6aa70b1edf
